### ISSUE TITLE
Swapped behavior for '360-days' and '365-days' financial year

### ISSUE THREAD

**Issue by MaksymNanyzniuk** [MaksymNanyzniuk/web.test#15]
PRECONDITIONS:
1. Open Deposit page.
2. Enter 100 into 'Deposit Amount' field. 
3. Enter 99 into 'Rate of interest' field.
4. Enter 360 into 'Investment Term' field.

CASE 1
1. Select radio button '360 days'.
AR: interest earned = 97.64.
ER: interest earnet = 99. 

CASE 2.
1. Select radio button '365 days'.
AR: interest earned = 99.
ER: interest earnet = 97.64.

**Comment by varajan** [comment]
Fixed
